config/routes.rb
Rails.application.routes.draw do
   get 'blogspot' => 'blogspot#index'
   get 'blogspot/new' => 'blogspot#new' 
   get 'blogspot/:id' => 'blogspot#show', as: 'blog'
   root 'blogspot#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blogspot.rb
class Blogspot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogspot_controller.rb
class BlogspotController < ApplicationController
    def index      
        @blogspots = Blogspot.all
    end
    def show 
        @blogspot = Blogspot.find(params[:id])
    end
    def new
        @blogspot = Blogspot.new
    end
    def create
        @blogspot = Blogspot.create(blog_params)
        if @blogspot.valid?
            redirect_to '/'
        end
    end

    private
    def blog_params
    params.require(:blogspot).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogspot_helper.rb
module BlogspotHelper
end

app/views/blogspot/index.html.erb
<h2> Articles  </h2>
<% @blogspots.each do |article| %>
<%= link_to article.title, blog_path(article) %>
<% end %>
<br>
<br>
<%= link_to 'Add New Article', 'blogspot/new' %>

app/views/blogspot/new.html.erb
<h2> Add new entry </h2>

<%= form_with(model: @blogspot,url: 'blogspot/new') do |form| %>

<br>
<%= form.label :title %>
<br>
<%= form.text_field :title %> 
<br>

<%= form.label :content %>
<br>
<%= form.text_field :content %>
<br>
<%= form.submit "Add" %>

<% end %>

app/views/blogspot/show.html.erb
<h1><%= @blogspot.title %></h1>
<p><%= @blogspot.content %><p>
<%= link_to 'home', '/' %>
<%= link_to 'Add New Article', 'blogspot/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>